version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass-loader
    versions:
    - ">= 11.a, < 12"
  - dependency-name: sass
    versions:
    - 1.32.5
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
