version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: docker-compose build --build-arg UID=$(id -u) --build-arg GID=$(id -g) web
      - run: docker-compose run --rm -T web composer install --no-interaction --no-progress

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: docker-compose run --rm -T web ./vendor/bin/phpunit tests/
      

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: docker-compose run --rm -T web yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: docker-compose run --rm -T web yarn production
